version: "build #{build}"

build: off

environment:
  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.
    - OS: Windows_NT
      PYTHON: "C:\\Python36-x64"
      TOOLSPATH: "C:\\mingw-w64\\x86_64-7.2.0-posix-seh-rt_v5-rev1\\mingw64\\bin;C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0\\bin"
      MAKE: mingw32-make
    - OS: Windows_NT
      PYTHON: "C:\\Python34-x64"
      TOOLSPATH: "C:\\mingw-w64\\x86_64-7.2.0-posix-seh-rt_v5-rev1\\mingw64\\bin;C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0\\bin"
      MAKE: mingw32-make
    - OS: Windows_NT
      PYTHON: "C:\\Python27"
      TOOLSPATH: "C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0\\bin"
      MAKE: make
    - OS: Windows_NT
      PYTHON: "C:\\Python34"
      TOOLSPATH: "C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0\\bin"
      MAKE: make
    - OS: Cygwin
      CYG_ROOT: "C:\\cygwin64"
      PYTHON: "C:\\cygwin64\\bin"
      PYTHON_VERSION: "2.7"
      ARCH: x86_64
      MAKE: make

before_build:
  - echo "Building Cysignals for %OS%"
  - set PATH=%PYTHON%;%PYTHON%\\scripts;%TOOLSPATH%;%PATH%
  - echo %PATH%
  - ps: >-
      if ( "$Env:OS" -ieq "Cygwin" ) {
          if ( $Env:PYTHON_VERSION[0] -ieq "2") {
              $python = "python"
          } else {
              $python = "python" + $Env:PYTHON_VERSION[0]
          }
          $python_exe = "python" + $Env:PYTHON_VERSION
          Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" `
              -OutFile "C:\get-pip.py"
          Start-Process -NoNewWindow -Wait `
              -FilePath $Env:CYG_ROOT\setup-$Env:ARCH.exe `
              -ArgumentList "-q -P $python,$python-devel,gcc-core,gcc-g++"
          & $python_exe "C:\get-pip.py"
      }
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - set CC=cl
  - appveyor DownloadFile https://anaconda.org/conda-forge/pthreads-win32/2.9.1/download/win-64/pthreads-win32-2.9.1-hfa6e2cd_3.tar.bz2 -FileName pthreads.tar.bz2
  - 7z x pthreads.tar.bz2
  - 7z x -oC:\pthreads pthreads.tar
  - xcopy C:\pthreads\Library\include\ %PYTHON%\include /E
  - xcopy C:\pthreads\Library\lib\ %PYTHON%\libs /E
  - xcopy C:\pthreads\Library\bin\ %PYTHON%\DLLs /E
  - cd C:\projects\cysignals
  - python%PYTHON_VERSION% -m pip install -r requirements.txt
  - python%PYTHON_VERSION% --version
  - python%PYTHON_VERSION% -m cython --version

build_script:
  - '%MAKE% -j4 install'

test_script:
  - '%MAKE% -j4 check-all'
  - '%MAKE% -j4 distcheck'

# Enable this to be able to login to the build worker. You can use the
# `remmina` program in Ubuntu, use the login information that the line below
# prints into the log.
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

